services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile.api

    ports:
      - "127.0.0.1:8080:8080"

    env_file:
      - ./backend/.env

    restart: unless-stopped

  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile.worker

    env_file:
      - ./backend/.env

    depends_on:
      - api

    restart: unless-stopped
